#!/bin/bash

x=$1
y=$2 
cols=$3
mp=$4
display=1


[ -z $x ] && x=19 # size x
[ -z $y ] && y=19 # size y
[ -z $cols ] && cols=8 # max color number
[ -z $mp ] && mp=50 # max path size

bx=$(($x/2))
by=$(($y/2))


./flood_create $x $y $cols > /tmp/board
cat /tmp/board | ./flood_solve -bx $bx -by $by -mp $mp > /tmp/answer
cat /tmp/answer /tmp/board | ./flood_print -bx $bx -by $by

