#!/bin/bash

tot=100000
inotifywait -q -e close_write -m --format "%w%f" challenge/out | while read filename; do 
	count=$(($count + 1))
	nl=$(($(wc -c < $filename) - 1))
	sum=$(($sum + $nl))
	avg=$(($sum * $tot / $count)) 
	printf "last one $filename=%d, estimation=%d\n" $nl $avg $maxp
done 
