#!/bin/bash

echo 100 > /tmp/maxp
./estimate-dyn & 
parallel --jobs 2 --eta "[ ! -f challenge/out/answer{} ] && cat challenge/in/flood{} | bin/flood_solve bx=9 by=9 mp=$(cat /tmp/maxp) > challenge/out/answer{}" ::: $(seq 1 100000)

