#!/bin/bash
find challenge/out/ -size 0 -delete
for i in $(seq 1 100000);do [ ! -f challenge/out/answer$i ] && echo $i;done|parallel --jobs 2 "cat challenge/in/flood{} | bin/flood_solve bx=9 by=9 mp=1200 > challenge/out/answer{}"

