#!/bin/bash

rm results
a="100 200 300 400 500 600 700 800 900 1000"
for i in $a;do
	rm -rf /tmp/challenge/out.$i/*
	mkdir -p /tmp/challenge/out.$i/
	parallel --jobs 4 --eta "cat /tmp/challenge/in/flood{} | bin/flood_solve bx=9 by=9 mp=$i > /tmp/challenge/out.$i/answer{}" ::: $(seq 1 100)
	avg=$(wc -c /tmp/challenge/out.$i/*|head -n -1|awk '{size+=$1-1;c++} END {printf "%0.0f",size*100000/c}')
	printf "maxpath=%d estimation=%d\n" $i $avg >> results
done

echo "Check file results"
